### ISSUE TITLE
Firefox not converting to .webp

### ISSUE THREAD

**Issue by fourroses666** [mplavala/webpconverter#13]
Any idea why it stopped working in firefox 132.0.1 (64-bits) on mac (12.7.6) EVO 3.1.29 CE. Chrome works.

**Comment by mplavala** [comment]
I verified this and Firefox stopped including `'image/webp'` in `$_SERVER['HTTP_ACCEPT']` header. This means that the plugin now does not know that Firefox supports WebP image format and thus sends the original image. I have not found any documentation as of why Firefox decided to do this, thus I will leave the thread open to see whether Firefox will fix this, or whether we will have to solve this in some other way.

WebP is supported on all major browsers, so we could default to always sending the WebP version. This would break the website on minority of outdated browsers, so this is not a solution I would be happy with. Other option is to add some exception for Firefox, but this would require sniffing the user's browser.

**Comment by fourroses666** [comment]
https://caniuse.com/webp

The only issue would be IE11, I guess, which is 11 years old. 
I'm oke with always serving webp but its up to you. 
If it can be fixed for FF then it would be even better.

AVIF seems to have the exame same support as webp which I didn't expected.
https://caniuse.com/avif

**Comment by mplavala** [comment]
Firefox did not change this behavior so I added a workaround for Firefox based on `HTTP_USER_AGENT` header.

Closed in 04fbb998209d2241204bbdfe6ff54fbc9f2de781.

**Comment by fourroses666** [comment]
Thanks!
