### ISSUE TITLE
Blanc website

### ISSUE THREAD

**Issue by fourroses666** [mplavala/webpconverter#2]
I had a blanc website a couple of times now, I really think it has to do with webp converter. Don't see any errors in the log.
Could be because of a "corrupt" file. I have updated the plugin now and will have a look if it will come back.

Just wanted to let you know and maybe you have experienced the same one before.

After Clear cache in manager it was oke again.

**Comment by mplavala** [comment]
I never encountered this problem.
There are few things tat come to my mind:
- On image-heavy sites on shared hosting, you can run out of memory when converting everything to WebP, I am preparing a fix for this.
- I haven't tested the plugin with PHP8 so far.
- DOMDocument can fail to generate the output, in that case you should only get `false` as output. I will add check to return the original HTML in case this happens.

Could you provide some more information to reproduce the bug?

**Comment by fourroses666** [comment]
All the info I have is that it happened after I did some editing on a couple of pages. All was oké and then an hour later the client gave me a message the site was blanc. Visited the website and it was indeed blanc. After clearing cache in the manager it was back online again. Had no time to check out what really was going on and actually don't know where to look for. No errors in log.

I did notice the client visited with www while I set .htaccess as all domain without but because of an update EVO 3.0.2 that file was overwritten :( I really don't think this was the issue.

**Comment by fourroses666** [comment]
The issue was there again. I looked at the source and there was some content / divs in it. So not totally blank.

Source:
![source](https://user-images.githubusercontent.com/523389/107887253-17d09f80-6f05-11eb-8937-f9e33de91fc6.jpg)

Template:
![template](https://user-images.githubusercontent.com/523389/107887254-18693600-6f05-11eb-9311-bdd777e9fcea.jpg)

I doubt it has to do with the [+mylang+]
Maybe I'm wrong with blaming webpconverter plugin, could be EVO too or that mylang snippet but I do kind of suspect webpconverter because the issue arrived not long after installing the plugin and didn't see this on other sites yet. 
Some other sites do have the webp plugin installed thow without having issues.

The mylang plugin is just (onwebpageinit):

	if(strstr($_SERVER['REQUEST_URI'], "/en/")) {
		$modx->setPlaceholder('mylang',"_en");
	}
	else {
		$modx->setPlaceholder('mylang',"");
	}

**Comment by mplavala** [comment]
So it looks like the chunks are not loaded correctly. Interesting.
I think this is some issue between WebP Converter and mylang (I used WebP Converter on pages with about dozen chunks and TVs with no issues). Does the mylang plugin include the switch statement as described [here](http://www.evolution-docs.com/documentation/developers-guide/plugins)? Also, why does it fire onWebPageInit? It would make more sense to me to fire it on OnParseDocument. See [here](https://docs.evo.im/en/03_develop/02_elements/04_plugins/02_plugin_events.html) for all EVO events.

**Comment by fourroses666** [comment]
Hmm, yes I think your right!
Its the custom mylang plugin which is the issue and not WebpConverter..
Don't know how to convert it to a "correct" plugin, I have set it on 'OnParseDocument' and keeping an eye on it.
Might need to rebuild the plugin :s
