### ISSUE TITLE
Issue with same-name.jpg and same-name.png

### ISSUE THREAD

**Issue by fourroses666** [mplavala/webpconverter#3]
When you have 2 files like img.png and img.jpg they both look the same ;-)
I think phpthumb fixes this by adding a random 3 characters to the name.

Don't know if there is a nicer solution and if you think this is a big deal.

**Comment by mplavala** [comment]
Actually, I fixed this yesterday. Now we simply map `img.png` to `img.png.webp`, names like these are going to be unique by construction. I also split away the function that constructs the file name for the WebP image, so if there will be any issue having multiple dots in names, or any other thing, one can simply change that function to do something else.
