### ISSUE TITLE
Call to undefined function webpconverter\mime_content_type()

### ISSUE THREAD

**Issue by scenduk** [mplavala/webpconverter#5]
I have this working well on several sites running php 7.4 with Evo 2 and 3, but on one site running php 7.2 and Evo 1.4.12 it returns this error. Is it the php version, Evo version or something else?

> Error : Uncaught Error: Call to undefined function webpconverter\mime_content_type() in /public_html/assets/plugins/webpconverter/plugin.webpconverter.php:41
> Stack trace:
> #0 /home/public_html/assets/plugins/webpconverter/plugin.webpconverter.php(11): webpconverter\convert('assets/images/i...')
> #1 /public_html/manager/includes/document.parser.class.inc.php(1919) : eval()'d code(18): webpconverter\serve_node(Object(DOMElement), 'src')
> #2 /public_html/manager/includes/document.parser.class.inc.php(1919): eval()
> #3 /public_html/manager/includes/document.parser.class.inc.php(5524): DocumentParser->evalPlugin('require_once(MO...', Array)
> #4 /public_html/manager/includes/document.parser.class.inc.php(978): DocumentParser->invokeEvent('OnWebPagePreren...', Array)
> #5 /public_html/manager/includes/document.parser.class.inc.php(2987): DocumentParser->outputContent()
> #6 /public_html/manager/includes/document.parser.class.in

Error information |  
-- | --
ErrorType[num] | ERROR[1]
File | /public_html/assets/plugins/webpconverter/plugin.webpconverter.php
Line | 41
Source | $srcMime = mime_content_type($src);
Current Plugin | WebP Converter(OnWebPagePrerender)

**Comment by mplavala** [comment]
This is a PHP/server problem. [mime_content_type](https://www.php.net/manual/en/function.mime-content-type.php) is a native PHP function that returns MIME type of file. You can try checking whether your server has all modules loaded (or ask your hosting).
I will add a check to test whether the function is defined in future update and try to get MIME type by different means to handle this edge case.

**Comment by scenduk** [comment]
Thanks, the host had to enable the fileinfo php extension, once done it's all working perfectly. Worth putting a check in there as it caused a blank 'Error' page for me - on a staging site so didn't matter but others might get worried.

**Comment by mplavala** [comment]
Exactly, this will only throw EVO warnings in the future and try to guess MIME type based on extension.
