### ISSUE TITLE
After update error

### ISSUE THREAD

**Issue by fourroses666** [mplavala/webpconverter#8]
```
« Evolution CMS Parse Error »
Too few arguments to function webpconverter\basic_checks(), 0 passed in 
/home/x/domains/x.nl/public_html/core/src/Core.php(1858)
 : eval()'d code on line 11 and exactly 1 expected

Error information |  
-- | --
File | /home/x/domains/x.nl/public_html/assets/plugins/webpconverter/plugin.webpconverter.php

```

**Comment by mplavala** [comment]
Try to update the plugin, it seems that the code of the plugin/snippet inside Evolution CMS did not update correctly. Optionally, you can check whether the plugin code inside Evolution CMS is the same as [this](https://github.com/mplavala/webpconverter/blob/master/install/assets/plugins/webpconverter.tpl) and the snippet code the same as [this](https://github.com/mplavala/webpconverter/blob/master/install/assets/snippets/webpBackground.tpl). In the plugin code the crucial change is on line 26, in the snippet code on line 20.

**Comment by fourroses666** [comment]
Yes the install on the Extras doesn't seem to install the plugin correct.
When I manually update the WebP folder in /plugins from github I get the same message.
But when I manually update the Plugin (and background snippet) in the manager it works again.

I think it would be possible to duplicate the plugin on update and be able to delete the old one afterwards. (if you know what I mean)

**Comment by mplavala** [comment]
I just tested this and on my dev server the Extras package manager correctly updates the plugin/snippet code. Maybe try checking whether your Extras work as they should.
Since this seems like Evolution CMS issue, I am marking it as closed.
